# This file was generated by GoReleaser. DO NOT EDIT.
cask "runware" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "e5cee35905e4fbd6daa825a9365ba6e7e8380a52fae8d9e467d729086d33af08"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_darwin_amd64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
    on_arm do
      sha256 "7811bcb35cbefff89a32970b203a4224607c49dca9f02651c5c49008fb8f78bf"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_darwin_arm64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "282db441e402282477f9ae1b607438e5f6cf8dc3c83628993f41465cba2600e5"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_linux_amd64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
    on_arm do
      sha256 "a8180a0d6b4522ec8f171968452ae70c2b6085c58bb66c5fd3b9d12e0a86966a"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_linux_arm64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
  end

  name "runware"
  desc "A command-line tool for interacting with the Runware inference API."
  homepage "https://runware.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runware"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runware"]
    end
  end

  # No zap stanza required

end
