# This file was generated by GoReleaser. DO NOT EDIT.
cask "runware" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "0f44a76fca071ba00e8cc1eea0417156b0d775ccddc631e75572525617839f79"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_darwin_amd64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
    on_arm do
      sha256 "2164582226a74bf6861e95d7d6ff575629d1a4d35bc0e4c1da6d6969f2d72e20"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_darwin_arm64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec6e30918da7a55eb54af7b808dad3c84b5ee523ac409a95e3c7bc995978bcf2"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_linux_amd64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
    on_arm do
      sha256 "f343e0c0ac5e269a10a868ef1c87e1f954caa91a18d38d3c2884b8a15774ab8d"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_linux_arm64.tar.gz",
        verified: "github.com/Runware/runware-cli/releases/download"
    end
  end

  name "runware"
  desc "A command-line tool for interacting with the Runware inference API."
  homepage "https://runware.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runware"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runware"]
    end
  end

  # No zap stanza required

end
