# This file was generated by GoReleaser. DO NOT EDIT.
cask "runware" do
  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "29e5032b1ac0528c9041584a8d82aa93ba6f03c9aed77446de5f6e36361509b1"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7e6fde2ad049117af627694d7242e6181b2e0a3d815f1d8176057652521e6250"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a3cb2c8c450aecde2a5ad11fb9f3a66b0ab8f8d98d9658ded3a65308afbc10f0"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3fefb84c0e1d46b1677b3258baeaf54419d5cce747b46d28869388cb278e5648"
      url "https://github.com/Runware/runware-cli/releases/download/v#{version}/runware_linux_amd64.tar.gz"
    end
  end

  name "runware"
  desc "A command-line tool for interacting with the Runware inference API."
  homepage "https://runware.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "runware"

  postflight_steps do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/runware"]
    end
  end

  # No zap stanza required
end
